export const selector = "body > div:nth-child(3) > div > div > div > div:nth-child(3) > div > div > div > div > div.grid__col.grid__col--desktop--4.grid__col--tablet--3.grid__col--mobile--1.desktop--order--0.tablet--order--0.mobile--order--0.desktop--align--auto.tablet--align--auto.mobile--align--auto > div > div > article > div.price-ticket__sentiment > div > span"
export const trend = "body > div:nth-child(3) > div > div > div > div:nth-child(3) > div > div > div > div > div.grid__col.grid__col--desktop--4.grid__col--tablet--3.grid__col--mobile--1.desktop--order--0.tablet--order--0.mobile--order--0.desktop--align--auto.tablet--align--auto.mobile--align--auto > div > div > article > div.price-ticket__sentiment > div > strong"
export const pair = [
"aud-cad",
"aud-chf",
"aud-jpy",
"aud-nzd",
"aud-usd",
"cad-chf",
"cad-jpy",
"chf-jpy",
"eur-aud",
"eur-cad",
"eur-chf",
"eur-jpy",
"eur-gbp",
"eur-nzd",
"eur-usd",
"gbp-aud",
"gbp-chf",
"gbp-jpy",
"gbp-nzd",
"gbp-usd",
"nzd-chf",
"nzd-jpy",
"nzd-usd",
"usd-cad",
"usd-chf",
"usd-jpy",
]
